ARG OWNER=skaha
ARG TAG=latest
ARG BASE_CONTAINER=${OWNER}/base:${TAG}

FROM ${BASE_CONTAINER}

USER ${NB_USER}
WORKDIR /tmp

COPY env.yml .
RUN mamba env update --quiet -n base --file env.yml \
    && mamba clean --all --quiet --force --yes \
    && jupyter lab build \
    && fix-permissions ${CONDA_DIR} \
    && fix-permissions /home/${NB_USER}

RUN npm cache clean --force \
    && rm -rf /home/${NB_USER}/.cache/yarn \
    && jupyter lab clean

COPY pinned .
RUN cat pinned ${CONDA_DIR}/conda-meta/pinned | uniq > pinned.new \
    && cp pinned.new ${CONDA_DIR}/conda-meta/pinned \
    && fix-permissions ${CONDA_DIR}

WORKDIR ${HOME}
